export const types = {
  upvoteEntry: "[Entry] Upvote",
  downvoteEntry: "[Entry] Downvote",
  getEntries: "[Entry] GetEntries",
  userLoggedIn: "[User] Logged",
  userLoggedOut: "[User] LoggedOut",
  addNewEntry: "[AddNewEntry] Add New Entry",
  setLoading: "[Entry] SetLoading",
  setOptionsClicked: "[Entry] SetOptionsClicked",
  setNewQuestion: "[Entry] SetNewQuestion",
  deleteEntry: "[Entry] Delete Entry",
  toggleSidebar: "[Sidebar] Toggle",
  changeUsername: "[Account] ChangeUsername",
  setPreviousPage: "[Auth] setPreviousPage",
  uploadProfilePicture: "[Account] UploadProfilePicture",
  addComment: "[Entry] AddComment",
  sentFriendRequest: "[Friend] SentFriendRequest",
  receivedFriendRequest: "[Friend] ReceivedFriendRequest",
  getFriendList: "[Friend] GetFriendList",
  acceptFriendRequest: "[Friend] AcceptFriendRequest",
  rejectFriendRequest: "[Friend] RejectFriendRequest",
  removeFriend: "[Friend] RemoveFriend",
  getFriendRequestsReceived: "[Friend] GetFriendRequestsReceived",
  openFriendRequests: "[Friend] OpenFriendRequestsReceived",
};
